/*
 * Exported lock/unlock funtions to use with JNI
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class com_gilecode_langlocker_LockEngine */
#include <jni.h>

#ifndef _Included_com_gilecode_langlocker_LockEngine
#define _Included_com_gilecode_langlocker_LockEngine
extern "C" {
/*
 * Class:     com_gilecode_langlocker_LockEngine
 * Method:    lockInputLanguage
 * Signature: (L)L
 */
JNIEXPORT jlong JNICALL Java_com_gilecode_langlocker_LockEngine_lockInputLanguage
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_gilecode_langlocker_LockEngine
 * Method:    unlockInputLanguage
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gilecode_langlocker_LockEngine_unlockInputLanguage
  (JNIEnv *, jclass);

}
#endif
